### ISSUE TITLE
Non-breaking spaces in names

### ISSUE THREAD

**Issue by firegurafiku** [odomanov/biblatex-gost#1]
Hi all!

Is there a way to force `biblatex-gost` package not to break line after initial letters in author names? In the attached example, how can I turn `G. K. Uskov` into `G.~K.~Uskov`?

![2016-08-29-145200_707x86_scrot](https://cloud.githubusercontent.com/assets/1611416/18051176/f5001d70-6e03-11e6-8092-8bbf83a508c7.png)

**Comment by Lenchik** [comment]
I think [minimal working example](http://meta.tex.stackexchange.com/questions/228/ive-just-been-asked-to-write-a-minimal-example-what-is-that) would be of help.

**Comment by odomanov** [comment]
This is controlled by a delimiter like `\bibnamedelima` or `\bibnamedelimb` or suchlike. I don't remember exactly which one, just read the biblatex manual.
