### ISSUE TITLE
 ShareLatex Инструкция по установке библиотеки

### ISSUE THREAD

**Issue by klouh** [odomanov/biblatex-gost#10]
Возможно дополнить файл справки инструкцией по прикручиванию вашей библиотеки к ShareLatex или другим популярным он-лайн сервисам?

**Comment by LSinev** [comment]
Она же уже много лет [выложена на CTAN](http://www.ctan.org/pkg/biblatex-gost) и, таким образом, входит во все популярные дистрибутивы. С чего вы взяли, что к [ShareLatex](https://ru.sharelatex.com) (а также [OverLeaf](https://www.overleaf.com/) и [Papeeria](https://papeeria.com/)) она не прикручена?

Сейчас на пробном файле проверил, всё хорошо подключается. На [ShareLatex](https://ru.sharelatex.com) `biblatex-gost` версии 1.12. Старовата версия, конечно, но это уже со службой поддержки сервиса нужно решать — чтобы они обновили пакеты у себя.

**Comment by odomanov** [comment]
@klouh, какая всё-таки требуется инструкция? Напишите, что у Вас не работает.

**Comment by ViRGiL175** [comment]
Добрый день.

Сейчас хотел сделать все красиво, получил вот такое:
![image](https://user-images.githubusercontent.com/11541555/35254250-e47a9592-0002-11e8-9ee3-9327b0bc2904.png)

Думаю, на самом деле было бы неплохо, если бы была документация, как использовать библиотеку в подобных редакторах, если они эту библиотеку не предоставляют, только у них и есть человеческое лицо на данный момент. 

Там можно загружать и подключать файлы, только вот полазил я по репозиторию, и не увидел даже намёка на расширение *.sty.

**Comment by LSinev** [comment]
@ViRGiL175  В примере вашем библиотека подключена неправильно, потому и ругается. Читайте русскую инструкцию к пакету `biblatex-gost`. `\usepackage{biblatex-gost}` писать не надо.

**Comment by ViRGiL175** [comment]
Ох, хорошо, спасибо, посмотрю.

Тогда, думаю, было бы здорово иметь ссылку на инструкции в ридми проекта, а то там только правовая информация. Чтоб, как говорится, прямо getting started. А то, раз иное не указано, пытаешься подключить как любой другой пакет.

Думаю, я не первый новичок, который даже ни разу не видел CTAN (если я вообще правильно нашёл), пользуясь только документацией ShareLatex и гуглением по Стековерфлоу.

**Comment by odomanov** [comment]
А вы работаете только с ShareLatex? Там можно найти документацию по пакетам? Без документации, действительно, сложно догадаться. Если вы собираетесь и дальше техом пользоваться, установите лучше Tex Live. Ну или ходите на CTAN.

В ридми проекта, кстати, написано "читайте документацию")))

**Comment by klouh** [comment]
Инструкция неплохая. Есть даже отдельный пдф-файл с примером источников литературы. Но хотелось бы типа мануала с инструкция-пример-результат, различными вариациями, типичными ошибками и способами их устранения. Да, я не профи, может даже и не любитель. Но это был бы неплохой вклад в популяризацию данного инструмента.

**Comment by klouh** [comment]
При подключении пакета переопределение команды перенаименование списка литературы перестало работать. Может это не только вашего пакета касается и вопрос стоит задавать на другом форуме? Какие части кода выложить чтобы диагностировать проблему. Проект большой.

**Comment by klouh** [comment]
При подключении пакета переопределение команды перенаименование списка литературы перестало работать. Может это не только вашего пакета касается и вопрос стоит задавать на другом форуме? Какие части кода выложить чтобы диагностировать проблему. Проект большой.

**Comment by odomanov** [comment]
Вы имеете в виду `\bibname`? Имейте в виду, что для классов типа `article` нужно менять `\refname`.

**Comment by odomanov** [comment]
Что касается популяризации, тут есть проблема, да. 
Это нужно писать отдельную книгу, причём, в основном, про библатех вообще. Я такую книгу для начинающих знаю только на французском языке: https://github.com/maieul/latexhumain.

**Comment by klouh** [comment]
В преамбуле
\documentclass[oneside,final,14pt]{extreport}
\usepackage[T1,T2A]{fontenc}
 \usepackage{mathptmx}
\usepackage[utf8]{inputenc}
\usepackage{float}
\titleformat{\chapter}[display]{\normalfont\bfseries}{}{0pt}{\huge}

\titlespacing*{\chapter}{0pt}{-50pt}{40pt}

\addto\captionsrussian{%
\def\contentsname{Содержание}% работает
\def\refname{ЛитератураДЛОДЛО}% не работает
}
% даём указание на включение данного место в оглавление как секции (\section)
\renewcommand{\bibname}{Whatever floats your boat}

Место вставки:
\printbibliography[title={title for bib}, heading=bibintoc] % печать библиографии
\addcontentsline{toc}{section}{Список используемой литературы}

**Comment by klouh** [comment]
Кстати, выделение жирным, курсивом тоже почему то не работает, как и \parencite, вместо этого  [KP1991].

**Comment by ViRGiL175** [comment]
> А вы работаете только с ShareLatex?

Нет, еще с Overleaf.

> Без документации, действительно, сложно догадаться. 

Дело не в догадках. Обычно пакеты подключаются неким попсовым образом. Когда видишь новый пакет, по аналогии пробуешь попсовый метод. Не выходит — идешь в репозиторий, глядишь в ридми, документацию. Обычно там есть Геттин Стартед, в котором обозначен необходимый минимум для запуска.

В этом репозитории я не увидел в документации каких-то особенностей по подключению, значит должен был сработать попсовый метод. Иначе было бы написано о каких-либо особенностях. Поэтому возник диссонанс и вопрос.

>  установите лучше Tex Live

Упаси аллах.

> "читайте документацию")))

Может в ридми зарядить ссылку прямо на документацию на CTAN или на страничку пакета?
