### ISSUE TITLE
Upcoming changes in biblatex 3.8

### ISSUE THREAD

**Issue by moewew** [odomanov/biblatex-gost#12]
You are probably already aware that `biblatex` is close to the release of version 3.8.

There are a few changes that are relevant for you (I might be missing something).

- `origlanguage` becomes a list
- `extrayear` becomes `extradate`
- `\DeclareSortingScheme` is now `\DeclareSortingTemplate`

The first one is a breaking change. For the second two backwards compatibility code is in place, but it would be appreciated if the new names would be taken up by style authors sooner rather than later.

The full list of changes can be found at https://github.com/plk/biblatex/blob/dev/doc/latex/biblatex/CHANGES.org and https://github.com/plk/biblatex/wiki

**Comment by odomanov** [comment]
Thank you, I'll check it.

**Comment by moewew** [comment]
Great!

Unfortunately, there are quite some serious build issues with Biber at the moment, which means that Biber 2.8 could not be released, so `biblatex` 3.8 cannot be used. TeX live and MikTeX have downgraded to 3.7 for the time being. You should probably wait to release a 3.8-ready version until Biber 2.8 can finally be released.

**Comment by odomanov** [comment]
Ah, this is probably why I'm having a bunch of strange errors. Ok, I'll wait.

**Comment by idamir** [comment]
JFYI, biber 2.10 has been released.

**Comment by odomanov** [comment]
Thank you for the reminder)))
I've seen the release of 2.9, but I was somewhat short of time. Now it's better, I hope, and I'll need to update the package. Thanks.
