### ISSUE TITLE
Реализация пп. 7.2.5.2 ГОСТ 7.1-2003

### ISSUE THREAD

**Issue by idamir** [odomanov/biblatex-gost#14]
В пп. 7.2.5.2 ГОСТ 7.1-2003 ([стр. 36](http://www.internet-law.ru/gosts/gost/1560/)) написано, что 
> Если сведения об ответственности составной части документа совпадают с заголовком библиографической записи, в аналитическом библиографическом описании они могут быть опущены.

Пример:

`Петров П. П. Название статьи / П. П. Петров // Название журнала. — 2001. — Т. 23. — С. 12321—12328.`

можно записать как

`Петров П. П. Название статьи // Название журнала. — 2001. — Т. 23. — С. 12321—12328.`

но по этому пункту не сокращается запись типа 

`Петров П. П. Название статьи / П. П. Петров, И. И. Иванов, С. С. Сидоров // Название журнала. — 2001. — Т. 23. — С. 12321—12328.`

Как реализовать это правило?

Я с горяча думал, что надо модифицировать макрос `byauthor`, но, как показал код ниже, никакого списка в этом макросе нет:
```
\renewbibmacro*{byauthor}{%
  \ifboolexpr{
    ( test \ifuseauthor
      and
      not togl {bbx:gostbibliography}
    )
    or
    test {\ifnameundef{author}}
    or
    test {\ifthenelse{\value{listtotal}<2}}
  }
    { \the\numexpr\value{listtotal}\relax}
    {\setrespdelim%
     \printnames[byauthor]{author}}}
```

**Comment by odomanov** [comment]
`\printnames` это и есть список.

А что, в случае одного автора всё работает?

**Comment by odomanov** [comment]
Кстати, если вы хотите использовать `listtotal` и пр., то это нужно делать в определении формата `byauthors`.

**Comment by idamir** [comment]
Давайте по порядку.
Что хочется:
статьи в формате `автор1. Название / Автор1, Автор 2, Автор 3 // далее по сценарию`
Сейчас это реализовано в таком виде:
В случае 1 автора: `автор1. Название / Автор1 // далее по сценарию`
если больше 2 автора: `автор1. Название / Автор1, Автор 2, Автор 3 // далее по сценарию`

Теперь если посмотрим на 7.2.5.2, то увидим, что можно так:
В случае 1 автора: `автор1. Название // далее по сценарию` <- вот это и хочется
если больше 2 автора: `автор1. Название / Автор1, Автор 2, Автор 3 // далее по сценарию`

**Comment by idamir** [comment]
Если в условии `\renewbibmacro*{byauthor}{`
тест `test {\ifthenelse{\value{listtotal}<2}}`
заменить на заведомо ложный, то код
`{ \the\numexpr\value{listtotal}\relax}`
выводит `0`, т.е. списка никакого нет в макросе `byauthor`. Можно ли в макрос передать список с авторами?
Как я понял, нет, нужно смотреть именно формат byauthor. А где он определён, чобы посмотреть на него и подправить?

**Comment by odomanov** [comment]
А вы не могли бы образец прислать для экспериментов? А то у меня не так, как у вас печатается.

> т.е. списка никакого нет в макросе byauthor

список есть внутри `\printnames`. Его можно вытащить, если исхитриться, но нужно как-то иначе делать.

**Comment by idamir** [comment]
test.tex
```
\documentclass[doctor]{disser}
\usepackage[T2A]{fontenc}
\usepackage[utf8]{inputenc}
\usepackage[english,russian]{babel}
\usepackage[style=gost-numeric,
  backend=biber,
  language=auto,
  hyperref=auto,
  autolang=other,
  sorting=none,
  natbib=true,
  movenames=false,
  maxnames=4,
  minnames=3,
  url=false,
  doi=false,
  eprint=true,
  related=true,
  mincrossrefs=99,
]{biblatex}
\addbibresource{test.bib}
\toggletrue{bbx:gostbibliography}
\DeclareFieldFormat{labelnumberwidth}{\mkbibbrackets{#1}}
\begin{document}
\phantom{\cite{Yoffe_1993_AP_42_173,Efros_1982_FTP_16_7_1209}}
\printbibliography[heading=bibintoc]
\end{document}
```

test.bib
```
@ARTICLE{Yoffe_1993_AP_42_173,
  author       = {A. D. Yoffe},
  title        = {Low-dimensional systems...},
  journal      = {Adv. Phys.},
  pages        = {173--266},
  volume       = {42},
  year         = {1993},
  language     = {english},
  langid       = {english},
}
@ARTICLE{Efros_1982_FTP_16_7_1209,
  author       = {{\relax Ал}. Л. Эфрос and А. Л. Эфрос},
  title        = {Межзонное поглощение света в полупроводниковом шаре},
  journal      = {Физика и техника полупроводников},
  year         = {1982},
  volume       = {16},
  number       = {7},
  pages        = {1209--1214},
  language     = {russian},
}
```

Элемент [1] попадает под 7.2.5.2

**Comment by odomanov** [comment]
Да, спасибо.

А вам обязательно нужно `\toggletrue{bbx:gostbibliography}`? Я правильно понимаю, что без этого всё выводится правильно?

**Comment by idamir** [comment]
без `bbx:gostbibliography` пример [2] формируется неправильно: ` Автор1, Автор 2, Автор 3. Название // далее по сценарию`.

Т.е. должно быть так: для [1] `bbx:gostbibliography=false`
для [2]  `bbx:gostbibliography=true`

**Comment by odomanov** [comment]
А вы по какому госту хотите оформить? По ГОСТ 7.0.5 так и должно быть. Учтите, что он в этом отличается от ГОСТ 7.1. По 7.1. автор в заголовке должен быть один, а по 7.0.5 может быть от одного до трёх.

**Comment by idamir** [comment]
Да, залип я на п. 4.10 ГОСТ 7.0.5. Согласен, надо форматировать по ГОСТ 7.0.5.
В связи с этим новый вопрос: а как быть, если автором больше 4-х? Согласно примерам в п. 5.3, их надо перенести в зону ответственности?

**Comment by odomanov** [comment]
Если вам всё-таки нужен ГОСТ 7.1, то нужно править формат:
`\DeclareNameFormat{byauthor}{...}`.
И здесь определены `listtotal` и пр. Но гост здесь не слишком ясен, и что конкретно делать, я плохо понимаю.

**Comment by odomanov** [comment]
> как быть, если автором больше 4-х? Согласно примерам в п. 5.3, их надо перенести в зону ответственности?

Да, в зону ответственности. И там сокращают с [и др.].

**Comment by idamir** [comment]
Спасибо. Разобрался. Выяснилось, что я пытался сделать ненужное.
