### ISSUE TITLE
footcite с пронумерованными сносками

### ISSUE THREAD

**Issue by vladkolotvin** [odomanov/biblatex-gost#16]
Как сделать библиографические ссылки в подстраничных сносках, но чтобы в тексте сноски обозначались цифрами?

**Comment by odomanov** [comment]
Честно говоря, вопрос не совсем понятен, но боюсь, что простого способа нет.

**Comment by vladkolotvin** [comment]
Добился нужного результата поставив стиль gost-numeric и использовав \fullfootcite.

**Comment by odomanov** [comment]
Хорошо, тогда я ветку закрываю.
