### ISSUE TITLE
Совместимость c пакетом gost

### ISSUE THREAD

**Issue by einhander** [odomanov/biblatex-gost#17]
Добрый день.
Если вопрос поднимался заранее прошу прощения.
Наша группа работает с одной базой библиографии в bib файле, многие для этого используют bibtex с пакетом gost.
В соответствии с документацией на этот пакет язык оригинала документа кодируется с помощью поля language, у вас в пакете за ту же функциональность отвечает поле langid.
Можно ли в вашем пакете создать алиас на на language, чтобы не добавлять двойную запись языка в базу данных?

**Comment by LSinev** [comment]
Лучше воспользуйтесь документацией `biblatex`  и задействуйте `Declaresourcemap`.

**Comment by einhander** [comment]
@LSinev спасибо, маны хоть иногда надо читать)))
