### ISSUE TITLE
Лишний отступ в сносках.

### ISSUE THREAD

**Issue by vladkolotvin** [odomanov/biblatex-gost#18]
При использовании опций
```
\usepackage[
    backend=biber,
    language=auto,
    autolang=other,
    style=gost-numeric
]{biblatex}
```
и использовании русских источников добавляются лишние отступы в сносках.
![2018-04-22 13 14 40](https://user-images.githubusercontent.com/768260/39094825-b7388224-463e-11e8-8b5d-776360f143ef.png)

У меня видно переопределен какой-то параметр, так как на чистом проекте воспроизвести не удалось.

Если использовать такие параметры:
```
\usepackage[
    backend=biber,
    style=gost-numeric
]{biblatex}
```
то biblatex считает все источники русскими:
![2018-04-22 15 09 48](https://user-images.githubusercontent.com/768260/39094856-3bf9e5ca-463f-11e8-9699-1958873053cc.png)

**Comment by vladkolotvin** [comment]
Методом тыка определил, что отступ добавляется из-за фикса для убирания точек после цифр в названии глав/разделов.
Почему-то данный кусок убирает точки в нумерации заголовков, но добавляет отступы в сносках:
```
\addto\russian@capsformat{
   \def\postchapter{\@aftersepkern}
   \def\postsection{\@aftersepkern}
   \def\postsubsection{\@aftersepkern}
   \def\postsubsubsection{\@aftersepkern}
}
```

**Comment by odomanov** [comment]
Попробуйте поставить % в конце всех строк.

**Comment by vladkolotvin** [comment]
К сожалению, не помогло. Пока что решил проблему, заменив указанный кусок кода на
```
\AtBeginDocument{%
    \def\postchapter{\hspace{0.5em}}%
    \def\postsection{\hspace{0.5em}}%
    \def\postsubsection{\hspace{0.5em}}%
    \def\postsubsubsection{\hspace{0.5em}}%
    \def\postparagraph{\hspace{0.5em}}%
    \def\postsubparagraph{\hspace{0.5em}}%
}
```

**Comment by vladkolotvin** [comment]
В принципе тему можно закрыть, если только кто-то не желает разобраться в проблеме до конца.

**Comment by odomanov** [comment]
закрываю
