### ISSUE TITLE
"Там же" для зарубежных источников. 

### ISSUE THREAD

**Issue by vladkolotvin** [odomanov/biblatex-gost#19]
При повторной сноске с зарубежным источником вставляется "Ibid" вместо "Там же".
<img width="530" alt="2018-05-13 21 41 34" src="https://user-images.githubusercontent.com/768260/39970604-f1dd777c-56f6-11e8-8ae8-8ad983eea4f4.png">
Как можно форсировать использование "Там же"?

**Comment by LSinev** [comment]
Думаю, Вам стоит посмотреть в [документации на `biblatex`](http://mirrors.ctan.org/macros/latex/contrib/biblatex/doc/biblatex.pdf) про разницу между `language` и `langid` и поправить что-нибудь (неясно, что именно стоит править, поскольку тут не телепаты, по крайней мере я, а Вы не удосужились приложить усилий, чтобы помочь другим помочь Вам, создав [минимальный воспроизводимый пример](https://tex.meta.stackexchange.com/a/3225/79756)).

**Comment by odomanov** [comment]
Это регулируется опциями `language` и `autolang`, а также полем langid в `bib` файле. Попробуйте их поменять, хотя я сам всегда пишу Ibid; так правильно, по моим представлениям.

**Comment by vladkolotvin** [comment]
<details>
<summary>Example code</summary>

```latex
\documentclass{article}

\usepackage{fontspec}
\setmainfont{Times New Roman}

\usepackage{csquotes}
\usepackage[english,russian]{babel}

\usepackage[
  backend=biber,
  language=auto,
  autolang=other,
  citestyle=gost-inline,
  bibstyle=gost-numeric,
  pagetracker=true,
  opcittracker=false
]{biblatex}

\begin{filecontents}{mybib.bib}

@article{Neusyhin1967,
	title = {Дофеодальный период как переходная стадия развития от родоплеменного строя к феодальному},
	year = {1967},
	author = {А. И. Неусыхин},
	journaltitle = {Вопросы истории},
	issue = {1},
	pages = {75-87},
	ISSN = {0042-8779},
	anguage = {russian},
  	langid = {russian}
}

@book{Fried1967,
	title = {The Evolution of Political Society: An Essay in Political Anthropology},
	year = {1967},
	author = {M. H. Fried},
	location = {NY.},
	publisher = {Random House},
	ISBN = {978-0394307879},
	pagetotal = {270},
	language = {english},
  	langid = {english}
}
\end{filecontents} 

\bibliography{mybib}

\begin{document}

\selectlanguage{russian}

<<Cite>>\smartcite{Neusyhin1967}

<<Cite>>\smartcite{Neusyhin1967}

<<Cite>>\smartcite{Neusyhin1967}

<<Cite>>\smartcite{Fried1967}

<<Cite>>\smartcite{Fried1967}

<<Cite>>\smartcite{Fried1967}

\end{document}
```
</details>

[untitled.pdf](https://github.com/odomanov/biblatex-gost/files/1999807/untitled.pdf)

Как сделать, чтобы для всех источников было "Там же"? И насколько это правильно?

**Comment by vladkolotvin** [comment]
Сменой параметров language и autolang я смог этого добиться, но зарубежные источники стали отображаться по русским правилам. Т.е. "под ред" вместо "ed by" и т.д.

**Comment by LSinev** [comment]
> "под ред" вместо "ed by" и т.д.
В примере выше не было такой записи, но попробуйте (предварительно удалив всякие *.aux и т. п. промежуточные файлы) в параметрах `language=autobib`, в самой записи с редактором `language = {english}` и `langid = {english}`.

**Comment by LSinev** [comment]
> "под ред" вместо "ed by" и т.д.

В примере выше не было такой записи, но попробуйте (предварительно удалив всякие *.aux и т. п. промежуточные файлы) в параметрах `language=autobib`, в самой записи с редактором `language = {english}` и `langid = {english}`.

**Comment by vladkolotvin** [comment]
> в параметрах language=autobib, в самой записи с редактором language = {english} и langid = {english}

Помогло на чистом документе. Но проблема осталась в моем основном документе. Проявляется в том, что у зарубежных источников указатель страницы пишется по русски("С." вместо "p."). Буду дальше копать. Если решу проблему, то напишу сюда.

**Comment by vladkolotvin** [comment]
Кстати последняя указанная проблема проявляется даже на чистом документе. Пример:
<details>
<summary>Example code</summary>

```tex
\documentclass{article}

\usepackage{fontspec}
\setmainfont{Times New Roman}

\usepackage{csquotes}
\usepackage[english,russian]{babel}

\usepackage[
  backend=biber,
  language=autobib,
  autolang=other,
  citestyle=gost-inline,
  bibstyle=gost-numeric,
  pagetracker=true,
  opcittracker=false
]{biblatex}

\begin{filecontents}{mybib.bib}

@article{Neusyhin1967,
	title = {Дофеодальный период как переходная стадия развития от родоплеменного строя к феодальному},
	year = {1967},
	author = {А. И. Неусыхин},
	journaltitle = {Вопросы истории},
	issue = {1},
	pages = {75-87},
	ISSN = {0042-8779},
	anguage = {russian},
  	langid = {russian}
}

@book{Fried1967,
	title = {The Evolution of Political Society: An Essay in Political Anthropology},
	year = {1967},
	author = {M. H. Fried},
	location = {NY.},
	publisher = {Random House},
	ISBN = {978-0394307879},
	pagetotal = {270},
	language = {english},
  	langid = {english}
}

@book{EarlyState1978,
	title = {The Early State: Models and Reality},
	year = {1978},
	editor = {H. J. M. Claessen and Peter Skalník},
	location = {The Hague},
	publisher = {Mouton Publishers},
	ISBN = {90 2797904 9},
	pagetotal = {689},
	language = {english},
  	langid = {english}
}
\end{filecontents} 

\bibliography{mybib}

\begin{document}

<<Cite>>\smartcite{Neusyhin1967}

<<Cite>>\smartcite{Neusyhin1967}

<<Cite>>\smartcite{Neusyhin1967}

<<Cite>>\smartcite{Fried1967}

<<Cite>>\smartcite{Fried1967}

<<Cite>>\smartcite{Fried1967}

<<Cite>>\smartcite[123]{EarlyState1978}

<<Cite>>\smartcite{EarlyState1978}

<<Cite>>\smartcite{EarlyState1978}

\end{document}
```
</details>

[untitled.pdf](https://github.com/odomanov/biblatex-gost/files/2000796/untitled.pdf)

**Comment by odomanov** [comment]
А что конкретно вы хотите сделать? Страницы при "Там же" на каком языке должны быть?

**Comment by vladkolotvin** [comment]
Хочу страницы при "Там же" на английском.

**Comment by odomanov** [comment]
Если вы хотите изменить только Ibid, то можно сделать
```latex
\renewcommand*{\mkibid}[1]{\foreignlanguage{russian}{Там же}}
```

**Comment by vladkolotvin** [comment]
Спасибо.
