### ISSUE TITLE
Сокращенная запись доктора наук

### ISSUE THREAD

**Issue by Lenchik** [odomanov/biblatex-gost#2]
По ГОСТ (ГОСТ Р 7.0.12-2011 СИБИД. Библиографическая запись. Сокращение слов и словосочетаний на русском языке) на сокращения доктор сокращается не `док.`, а `д-р`.

> доктор 
>   д-р 
> Условие применения:   в названии ученой степени
> 
> документ 
>   док. 

Не знаю из этого пакета или из самого библатеха идёт, но хорошо бы исправить. И, если можно, временный костыль для преамбулы пока до CTAN обновление дойдёт.

**Comment by odomanov** [comment]
Да, спасибо, я исправлю.

В преамбуле попробуйте написать 

``` latex
\DefineBibliographyStrings{russian}{%
 docthesis        = {дис\adddotspace\textellipsis\ д-ра},
 docautoref       = {автореф\adddotspace дис\adddotspace\textellipsis\ д-ра},
}
```

**Comment by odomanov** [comment]
Исправлено
