### ISSUE TITLE
Экспорт в \bibitem

### ISSUE THREAD

**Issue by nickkolok** [odomanov/biblatex-gost#20]
Доброго времени суток!

Отдельные журналы принимают библиографию только в виде
```
\begin{thebibliography}{99}
\bibitem{smth}
...
\end{thebibliography}

Существует ли способ конвертировать `.bbl`-файл, выдаваемый `biblatex-gost`, в такой формат?

**Comment by odomanov** [comment]
Простого способа, похоже, нет: https://tex.stackexchange.com/questions/12175/biblatex-submitting-to-a-journal.

**Comment by nickkolok** [comment]
@odomanov, а насколько реально сделать опцию, которая выведет tex-код с \bibitem прямо в пдф?

**Comment by odomanov** [comment]
Не знаю, это нужно авторов библатеха спрашивать. Выводить просто в файл они говорят нельзя: https://github.com/plk/biblatex/issues/292.
А в pdf, может быть и можно. Есть стили, которые имитируют  bibtex, возможно, их можно как-то использовать.

**Comment by nickkolok** [comment]
@odomanov, а можно допилить стиль так, чтобы он в pdf выводил перед каждым пунктом текст `\bibitem` и соответствующую метку?

**Comment by nickkolok** [comment]
А если ещё и сможет вместо выделения курсивом выводить `\textit` - будет более чем работоспособно.

**Comment by odomanov** [comment]
Вообще, это интересно. Попробуйте вот это в преамбуле:

```latex
\defbibenvironment{bibliography}
  {\printtext{\textbackslash begin\textbraceleft thebibliography\textbraceright}%
   \list{}{}}
  {\endlist%
   \printtext{\textbackslash end\textbraceleft thebibliography\textbraceright}}
  {\item \textbackslash bibitem [\printfield{entrykey}]}
```

**Comment by odomanov** [comment]
А для `biblatex-gost` добавьте ещё.

```latex
  \renewcommand*{\mkgostheading}[1]{%
    \textbackslash textit\textbraceleft #1\textbraceright}
```

**Comment by odomanov** [comment]
Что-то я совсем забыл синтаксис. Должно быть вот так:
```latex
\defbibenvironment{thebibliography}
  {\textbackslash begin\{thebibliography\}\{99\}
   \renewcommand*{\mkbibemph}[1]{\textbackslash emph\{##1\}}%
   \renewcommand*{\mkbibitalic}[1]{\textbackslash textit\{##1\}}%
   \renewcommand*{\mkbibbold}[1]{\textbackslash textbf\{##1\}}%
   \list{}{}}
  {\endlist
   \textbackslash end\{thebibliography\}}
  {\item\textbackslash bibitem\{\printfield{entrykey}\}\\}
```
И потом выводится как
```latex
\printbibliography[env=thebibliography]
```

Upd: Немного поправил, должно работать для всех стилей, не только `biblatex-gost`.

Вообще, получается супер-способ, надо о нём на stackexchange написать.

**Comment by odomanov** [comment]
Написал авторам: https://github.com/plk/biblatex/issues/292#issuecomment-414399008.

**Comment by odomanov** [comment]
Авторы энтузиазма не показали, похоже, это слишком сложно. Но в большинстве случаев, я думаю, можно так использовать. 

Я выше немного подредактировал, добавил удобств.

**Comment by LSinev** [comment]
Предлагаю эту идею описать в документации следующего релиза `biblatex-gost`.

**Comment by odomanov** [comment]
@nickkolok, скажите, пожалуйста, что вы думаете о способе. Я сам в такие журналы не посылаю, поэтому не знаю, годится ли он в таком виде.

**Comment by nickkolok** [comment]
@odomanov, большое спасибо! Есть некоторые проблемы, в частности,  приходится перевбивать формулы. Но это мелочи. Считаю, что способ нужно однозначно описать в документации. Добавил подавление колонтитулов, номеров страниц и переносов, иначе копировать совсем неудобно.

```
\defbibenvironment{thebibliography}
  {\textbackslash begin\{thebibliography\}\{99\}
   % Page numbers and page headings are not wanted when copying
   \thispagestyle{empty}
   \pagestyle{empty}
   \hyphenpenalty=10000
   \exhyphenpenalty=10000
   \renewcommand*{\&}{\textbackslash \symbol{38}}%
   \renewcommand*{\mkbibemph}[1]{\textbackslash emph\{##1\}}%
   \renewcommand*{\mkbibitalic}[1]{\textbackslash textit\{##1\}}%
   \renewcommand*{\mkbibbold}[1]{\textbackslash textbf\{##1\}}%
   \list{}{}}
  {\endlist
   \textbackslash end\{thebibliography\}
   \thispagestyle{empty}
   \pagestyle{empty}
  }
  {\item\textbackslash bibitem\{\printfield{entrykey}\}\\}

```

Если бы речь шла об экосистеме `npm` - уже пилил бы отдельный маленький пакет.

**Comment by nickkolok** [comment]
Везёт же мне на небиблатехные журналы, однако!

Существующий метод, хотя и решает много проблем, вынуждает перевбивать формулы. (Если быть совсем честным,  то ещё и диакритика превращается в юникод). Есть ли какой-то способ экранировать названия статей типа \detokenize ([пишут](https://tex.stackexchange.com/questions/485896/alternative-to-detokenize-working-with-special-unicode-characters), что у него проблемы с юникодом) или \verb (который в принципе не очень понятно, как использовать) ?

И чтоб не постить два раза: @odomanov , можно я запилю-таки маленький пакетик с нашим костылём?

**Comment by odomanov** [comment]
Пилите, конечно, кто ж вам помешает... )))

Я не очень понимаю проблему. Ваш журнал хочет не юникод, а у вас оригинал в юникод?

**Comment by nickkolok** [comment]
Мой журнал согласен на юникод, мои .bib-файлы в юникоде, я люблю юникод, юникод любит меня.

BiBTeX не любит юникод (или я неправ?), зато его любит biblatex. Это и было для меня решающим аргументом в пользу biblatex.

Журнал не любит biblatex, но у нас есть костыль от предыдущего журнала. Костыль хорош всем, кроме того, что он рендерит формулы. А хотелось бы вместо формул видеть их исходный код, чтобы его копировать.

Я предполагаю пустить в ход \detokenize, но есть инфа, что он не дружит с юникодом. Есть ли более адекватные способы?

**Comment by nickkolok** [comment]
Для истории: бибтех на юникоде таки завёлся (странно) и даже с amsrefs, но почему-то работает как-то не так. Продолжаю творить чёрную магию. \detokenize действительно превращает кириллицу в суровые кондовые крякозябры, но есть вот такая магия:
```
\newcommand{\utffriendlydetokenize}[1]{
	\scantokens{
		\catcode`\_=12
		\catcode`\^=12
		\catcode`\{=12
		\catcode`\}=12
		\catcode`\&=12
		\catcode`\$=12
		\catcode`\\=12
		#1
	}
}

```

**Comment by nickkolok** [comment]
Итак, на данный момент вот эта конструкция устраивает меня чуть менее, чем полностью:
```

\defbibenvironment{bibitembibliography}
  {\textbackslash begin\{thebibliography\}\{99\}
   % Page numbers and page headings are not wanted when copying
   \thispagestyle{empty}
   \pagestyle{empty}
   \hyphenpenalty=10000
   \exhyphenpenalty=10000
   \renewcommand*{\&}{\textbackslash \symbol{38}}%
   \renewcommand*{\mkbibemph}[1]{\textbackslash emph\{##1\}}%
   \renewcommand*{\mkbibitalic}[1]{\textbackslash textit\{##1\}}%
   \renewcommand*{\mkbibbold}[1]{\textbackslash textbf\{##1\}}%
   %\DeclareFieldFormat{titlecase}{\texttt{\utffriendlydetokenize{#1}}}
   \list{}{}}
  {\endlist
   \textbackslash end\{thebibliography\}
   \thispagestyle{empty}
   \pagestyle{empty}
  }
  {\item~\\~\textbackslash bibitem\{\printfield{entrykey}\}\\}

\newcommand{\utffriendlydetokenize}[1]{
	\scantokens{
		\catcode`\_=12
		\catcode`\^=12
		\catcode`\{=12
		\catcode`\}=12
		\catcode`\&=12
		\catcode`\$=12
		\catcode`\#=12
		\catcode`\\=12
		#1
	}
}



\newcommand{\printbibitembibliography}{
	\DeclareFieldFormat{titlecase}{\texttt{\utffriendlydetokenize{##1}}}
	\DeclareDelimFormat[bib]{nametitledelim}{\newline\bibsentence}
	\printbibliography[block=par,env=bibitembibliography]
}
```

Вставлять в конец документа командой `\printbibitembibliography`.

Не устраивает:

1. Отсутствие переноса строки между названием статьи и названием журнала (он там был бы весьма кстати, чтобы при копировании в файл разрывы строк стояли красиво)

2. Невозможность запихать `\DeсlareFieldFormat` внутрь `\defbibenvironment` (почему-то выдаёт ошибку). Сейчас всё это дело категорически рекоменуется ставить только в конце документа или вместо нормальной библиографии.

Станет чуть посвободнее со временем - оформлю .sty в отдельную репу.

**Comment by LSinev** [comment]
@nickkolok Сейчас самое время, чтобы не затягивать с выкладыванием нового пакета на CTAN: _доводы из сообщения_ https://github.com/odomanov/biblatex-gost/issues/22#issuecomment-590053913
Ещё обратите внимание на будущие изменения в версии 3.15 `biblatex` https://github.com/plk/biblatex/blob/dev/doc/latex/biblatex/CHANGES.md#release-notes-for-version-315 — вдруг, что-то у Вас задействовано.
`\DeclareFieldFormat`, вроде бы, можно помещать в _configuration file_ `biblatex.cfg`.
По поводу переноса строки можете обратить внимание на https://tex.stackexchange.com/questions/228774/linebreak-in-biblatex-citation и схожие вопросы на том ресурсе.

**Comment by nickkolok** [comment]
@LSinev, спасибо за новость, но у меня опыта работы с CTAN нет вообще; я не успею за 4 дня написать документацию, разобраться с `.dtx` и вот этим вот всем. Под "пилить пакетик" я имел в виду всего-навсего "выложить на гитхаб .sty-файл и простенький реадмишник к нему". Если всё критично - готов передать код в `biblatex-gost` (LPPL же, да?). 
<details>
  <summary>Current version</summary>
  
  ```latex
  \NeedsTeXFormat{LaTeX2e}[1994/06/01]
\ProvidesPackage{biblatex2bibitem}
  [2020/02/24 v0.01 LaTeX package to convert biblatex-generated bibliography to bibitem commands]

\RequirePackage{biblatex}

\defbibenvironment{bibitembibliography}
  {\textbackslash begin\{thebibliography\}\{99\}
   % Page numbers and page headings are not wanted when copying
   \thispagestyle{empty}
   \pagestyle{empty}
   \hyphenpenalty=10000
   \exhyphenpenalty=10000
   \renewcommand*{\&}{\textbackslash \symbol{38}}%
   \renewcommand*{\mkbibemph}[1]{\textbackslash emph\{##1\}}%
   \renewcommand*{\mkbibitalic}[1]{\textbackslash textit\{##1\}}%
   \renewcommand*{\mkbibbold}[1]{\textbackslash textbf\{##1\}}%
   %\DeclareFieldFormat{titlecase}{\texttt{\utffriendlydetokenize{#1}}}
   \list{}{}}
  {\endlist
   \textbackslash end\{thebibliography\}
   \thispagestyle{empty}
   \pagestyle{empty}
  }
  {\item\%\\~\textbackslash bibitem\{\printfield{entrykey}\}\\}

\newcommand{\utffriendlydetokenize}[1]{
	\scantokens{
		\catcode`\_=12
		\catcode`\^=12
		\catcode`\{=12
		\catcode`\}=12
		\catcode`\&=12
		\catcode`\$=12
		\catcode`\#=12
		\catcode`\\=12
		#1
	}
}



\newcommand{\printbibitembibliography}{
	\raggedright
	\DeclareFieldFormat{titlecase}{\utffriendlydetokenize{##1}}
	%\DeclareDelimFormat[bib]{nametitledelim}{\newline\bibsentence}
	\printbibliography[env=bibitembibliography]
}

  ```
  
</details>

Про совместимость посмотрел. Вроде ломающих изменений немного и они нашего костылика не касаются.

За ссылку спасибо. Её я уже видел. Насколько я понял, поменять это на уровне отдельной библиографии нельзя, т.е. вот так не сработает:
```latex
	\printbibliography[block=par,env=bibitembibliography]
```
Только вот так:
```latex
\usepackage[block=par,...]{biblatex}
```
Это можно описать в документации. Печально, что при таком указании исчезает возможность одновременно собирать документ с "нормальной" и "копируемой" библиографиями.

**Comment by odomanov** [comment]
`.dtx` не обязателен: https://ctan.org/help/upload-pkg. Достаточно sty-файла и документации. Они пакуются в zip и загружаются через форму. Там всё очень просто. 

Отдельный пакет лучше, т.к. он, по идее, годится не только для `biblatex-gost`, а вообще для `biblatex`.

**Comment by LSinev** [comment]
Может быть, даже можно обновить информацию в https://github.com/plk/biblatex/issues/292 и https://github.com/plk/biblatex/issues/783, и получить какие-нибудь комментарии от разработчиков `biblatex` по текущей реализации из https://github.com/odomanov/biblatex-gost/issues/20#issuecomment-590290942. Из обсуждений (особенно https://github.com/plk/biblatex/issues/783#issuecomment-414925252) видно, что есть много подводных камней, и простого внедрения не будет, но сейчас, с активным впиливанием latex3 функционала, возможно, что-то обновилось по возможностям.

**Comment by nickkolok** [comment]
Т.е. хватит простого README.md с коротенькой документацией и собственно .sty-файла? Звучит гораздо реалистичнее!

**Comment by nickkolok** [comment]
Не уверен, что успел в сроки, но вот оно: https://ctan.org/pkg/biblatex2bibitem
Будет обновляться, разумеется (надеюсь).
Репозиторий: https://gitlab.com/Nickkolok/biblatex2bibitem

**Comment by nickkolok** [comment]
Работа кипит, даже промелькнул первый фичреквест.
Однако, возможно, кто-то из вас может подсказать что-нибудь хорошее на тему того, с чем я сам пока не справился: https://gitlab.com/Nickkolok/biblatex2bibitem/issues
