### ISSUE TITLE
Форма отчета о НИР

### ISSUE THREAD

**Issue by konstantin-morenko** [odomanov/biblatex-gost#21]
Предлагаю добавить в документацию оформление ссылок на отчет о НИР.  Только нужные еще поля руководителя, исполнителей, № госрегистрации и инвентарного.

**Comment by LSinev** [comment]
Было бы замечательно, если бы Вы в этом помогли автору пакета:
1. Сформировали несколько bib-записей с примерами (разное количество авторов, привязанные ссылки на онлайн размещение (url, doi, возможно url и doi одновременно), есть ли разница в отчетах по НИР, ОКР, НИОКР).
2. Указали бы какие поля в записи существуют всегда (учитывая случаи ссылок на отчеты советского времени. которые могли иметь другие выходные данные по нормативам того времени, например https://search.rsl.ru/ru/record/01007130696, https://search.rsl.ru/ru/record/01007236075).
3. Сформировали бы соответствующие этим bib-записям желаемые результаты работы пакета.
