### ISSUE TITLE
После обновления TeX Live 2019 (или biblatex до 3.13a) примеры из пакета не компилируются

### ISSUE THREAD

**Issue by LSinev** [odomanov/biblatex-gost#22]
Ошибка: `Package inputenc Error: Unicode character  (U+0084)`
Компилирую `biblatex-gost-examples.tex` с помощью pdflatex, biber 2.13, biblatex 3.13a.

```tex
% !TeX program = pdflatex 
\RequirePackage{filecontents}
\begin{filecontents*}{biblatex_number_check.bib}
@ARTICLE{Nasirova,
    author = {Насырова, Г. А.},
    title = {Модели государственного регулирования страховой деятельности},
    journal = {Вестник Финансовой академии},
    year = {2003},
    number = {4},
    langid = {russian}
}

\end{filecontents*}

\documentclass[a4paper, 12pt]{article}

\usepackage[T2A]{fontenc}                         % Поддержка русских букв
\usepackage[utf8]{inputenc}                       % Кодировка utf8
\usepackage[english, russian]{babel}              % Языки: русский, английский
\usepackage[%
backend=biber,% движок
bibencoding=utf8,% кодировка bib файла
sorting=none,% настройка сортировки списка литературы
style=gost-numeric,% стиль цитирования и библиографии (по ГОСТ)
clearlang=true,% внутренний сброс поля language, если он совпадает с языком из babel/polyglossia
]{biblatex}

\addbibresource{biblatex_number_check.bib} 

\begin{document}
\nocite{*}
\printbibliography
\end{document}
```

В этом примере, если у записи закомментировать `number`, то не проявляется ошибка.
Аналогично не проявляется, если переделать пример под lulalatex|xelatex и polyglossia.

Возможно, связано с тем, что number с какого-то момента стал `literal` в `biblatex` и на это наложились какие-то нововведения.

**Comment by odomanov** [comment]
Почему-то символ № перестал работать в pdflatex. Работает `\textnumero`, но нужен пакет `textcomp`.

**Comment by LSinev** [comment]
Надо подключить `textcomp` и тогда заработает?
Может это какая-то проблема/нововведение в [`babel`](https://github.com/latex3/babel) поддержке русского языка? Там как-то раньше выпиливали `\No`, а теперь может с самим символом/кодом намудрили (как бы это проверить)?

Возможно, это не единственный проблемный символ, поскольку в связи с созданием pdf/a документов в 2018 году был актуален такой код, а сейчас, может, это для всех документов понадобится. Но он не с babel связан, а с `t2a`:
```tex
%%% Solving \textnumero problem in russian pdflatex
%%% Don't know how to explain why this works
\UndeclareTextCommand{\textnumero}{T2A}
\UndeclareTextCommand{\S}{T2A}
\UndeclareTextCommand{\textpertenthousand}{T2A}
\usepackage{textcomp} %depending on previous font packages this may be second call to package
```

**Comment by odomanov** [comment]
Непонятно, может быть баг в `inputenc`. В таких случаях `\DeclareUnicodeCharacter` должно помогать, но почему-то не помогает.

Подключения `textcomp` недостаточно, нужно ещё добавить в преамбулу `\DefineBibliographyStrings{russian}{number={\textnumero}}`.

**Comment by LSinev** [comment]
> Почему-то символ № перестал работать в pdflatex

> может быть баг в inputenc

Может быть, это связано с подготовкой к грядущим изменениям:
https://www.latex-project.org/news/2020/01/17/latex-dev-2020-2/
https://www.latex-project.org/news/2019/11/28/latex-dev-2020-2/
https://www.latex-project.org/publications/2019-FMi-TUB-tb125mitt-dev-format.pdf
https://www.latex-project.org/news/latex2e-news/ltnews30.pdf
https://www.latex-project.org/publications/2019-08-FMi-TUG-Taming-utf8.pdf

**Comment by odomanov** [comment]
Посмотрите ещё вот сюда: https://github.com/plk/biblatex/issues/960.

**Comment by LSinev** [comment]
Я посмотрел, но не понял причину. Раньше же работало. Хочется понять, хотя бы, какое изменение и в каком пакете привело к такому состоянию. И, как я понимаю, в самом тексте использовать `№` можно свободно, а вот если задействован `biblatex`, то уже нельзя.

**Comment by odomanov** [comment]
В тексте № можно ипользовать. Проблема возникает (по крайней мере, насколько мне известно), когда нужно применить к № капитализацию, например, после точки. Тогда в `pdflatex` возникает проблема с юникодом. Подробностей я не понимаю, и почему вдруг эта проблема появилась --- тоже. Что здесь можно сделать, тоже непонятно. Но вроде бы это должно скоро решиться с переходом на `l3`.

**Comment by LSinev** [comment]
Предлагаю рассмотреть возможность добавить в `biblatex-gost` такую (или типа такой, например с открытой датой "справа") заглушку для этой, пусть и внешней для пакета, проблемы (дополнительных пакетов подгружать не надо, всё и так подгружает `biblatex`):
```tex
\ifpdftex
\makeatletter
    \ltx@ifpackagelater{biblatex}{2020/02/23}{
        \typeout{Assuming this version of biblatex works with № sign correctly.}
    }{
        \ltx@ifpackagelater{biblatex}{2019/08/31}{
            \typeout{Assuming this version of biblatex works with № sign incorrectly. Applying patch}
            \DefineBibliographyStrings{russian}{number={\textnumero}}
        }{}
    }
    \makeatother
\fi
```
Доводы за:
* Совсем скоро закроют (http://www.tug.org/texlive/) возможность обновлений TL2019  и может быть ситуация, что полностью обновленный TeXLive 2019 не сможет компилировать старые, не подозревающие об этой проблеме, документы (а ошибка неинформативная).
* Неизвестно, когда именно зарелизят `biblatex` 3.15 и будет ли он действительно решать эту проблему. 
* Есть большой шанс, что эта проблема перетечет в официальный финальный DVD релиз TL2020, если её как-то не решить сейчас.
* Совсем скоро зафинализируют пакеты для long term support релизов linux (типа Ubuntu 20.04 LTS и производных) и судя по тому, как не торопятся делать багфикс релизы старшие пакеты, хотя бы в этой части `biblatex-gost` как дефакто единственный актуальный пакет для русской библиографии мог бы помочь.

**Comment by odomanov** [comment]
Я добавил и на CTAN послал. 

Для версий Biblatex ниже 3.14 патч применить не получается, поэтому 3.14 теперь минимальная требуемая версия.

**Comment by Savvig** [comment]
Просьба убрать или сделать возможным отключить предупреждение

«Applying temporary patch for Unicode symbols. For details see biblatex issue #960»

Предупреждение сбивает с толку, приходится всё время помнить, что оно не связано ни с какими проблемами в документе (или заново искать информацию по нему в интернете).

Насколько я понял, проблема в biblatex была решена: https://github.com/plk/biblatex/issues/960

Но даже если сам патч всё ещё необходим, предупреждение для пользователя, как мне кажется, излишне.

**Comment by odomanov** [comment]
Да, я отключу для новых версий biblatex.

**Comment by odomanov** [comment]
Для biblatex 3.15+ отключил и предупреждение и сам патч.
