### ISSUE TITLE
Переносы

### ISSUE THREAD

**Issue by burrbull** [odomanov/biblatex-gost#23]
Здравствуйте.

Можно ли как-то сделать, чтобы не разрывало инициалы и номера.
Использовать, например, `~` или `\,` вместо пробелов?

**Comment by odomanov** [comment]
Что-то я не понимаю, о каких номерах речь. Можно поподробнее?

**Comment by burrbull** [comment]
`number`, `issue`, чтобы между знаком `№` и числом нельзя было сделать перенос (в смысле разрыв строки). Ну и в инициалах тоже.

**Comment by burrbull** [comment]
Еще вспомнил. Если много авторов, сокращает до `[и др.]`.

Для иностранной литературы тоже. Поле `language` никак не влияет.
Должно быть наверное `[et al.]` или что-то подобное.

**Comment by odomanov** [comment]
Между № и номером стоит `\addabbrvspace`, переносы на котором регулируются счётчиком `abbrvpenalty`. Если вы хотите их совсем запретить, должно помочь вот это: `\defcounter{abbrvpenalty}{10000}`. Но учтите, что это на некоторые другие переносы тоже повлияет.

Между инициалами стоит команда `\bibinitdelim`, она уже, вроде бы, должна быть неразрывным пробелом. Но попробуйте утановить: `\renewrobustcmd*{\bibinitdelim}{~}`.

Насчёт "и др.": нужно устанавливать поле `langid`. Поле `language` обычно используется просто для вывода, а в `biblatex-gost` вообще не используется.

**Comment by burrbull** [comment]
Спасибо, попробую.

**Comment by burrbull** [comment]
Похоже рвет между инициалами и фамилией, а это тоже недопустимо.

**Comment by odomanov** [comment]
Посмотрите документацию, там для имён определено много разных команд, и всё можно регулировать.

**Comment by LSinev** [comment]
@burrbull Как найдёте решение всех описанных вопросов, опишите его здесь (в духе «в преамбулу, после вызова `biblatex` нужно добавить следующие строки...»), пожалуйста. Думаю, пригодится не только Вам.

**Comment by burrbull** [comment]
`[et al.]` починил только что. Пришлось обновить `texlive`.
Старая версия видимо плохо работала с `polyglossia`. Ну и нужно
`\setotherlanguage{english}` конечно же.

**Comment by burrbull** [comment]
Список литературы у меня почти в самом конце, поэтому перед ним добавил как посоветовали:
```
\renewrobustcmd*{\bibinitdelim}{\,}
\defcounter{abbrvpenalty}{10000}
```

Но
> Похоже рвет между инициалами и фамилией, а это тоже недопустимо.

пока не решил.
