### ISSUE TITLE
Запятая после фамилии в gostbibliography

### ISSUE THREAD

**Issue by burrbull** [odomanov/biblatex-gost#24]
У нас сейчас в диссертациях используется ГОСТ 7.0.1 2003, но при этом между фамилией и инициалами ставится запятая:
```
1. Фамилия, И. О. Название / И. О. Фамилия 
```

Можно ли как-то опционально добавить эту запятую?
Заранее спасибо.

**Comment by LSinev** [comment]
Так помогает? (https://tex.stackexchange.com/a/17593)
```tex
\toggletrue{bbx:gostbibliography}
\renewcommand*{\revsdnamepunct}{\addcomma}
```

В целом, для диссера по ГОСТ (насколько это вообще возможно) можно воспользоваться https://github.com/AndreyAkinshin/Russian-Phd-LaTeX-Dissertation-Template

**Comment by burrbull** [comment]
Да, помогло. Спасибо.

Можно последний вопрос? Есть ли поле, отвечающее за такую штуку как "Режим доступа"?
Это для электронных ресурсов.

**Comment by LSinev** [comment]
Документация у пакета довольно хорошая ;)
http://mirrors.ctan.org/macros/latex/contrib/biblatex-contrib/biblatex-gost/doc/biblatex-gost.pdf#page=9
Поле `media`, по таблице можно заполнить требуемым значением.

**Comment by burrbull** [comment]
Про media знаю.
Тут вот такие извращения:
```
301. Tender.Pro–Электронная  торговая  площадка  [Электронный  ресурс]  : сайт. –Долгопрудный, 2017. –Режим доступа: http://tender.pro, свободный. –Загл. с экрана.
```
Вместо `url` пишут `Режим доступа`, а потом еще уточняют `свободный`.

**Comment by LSinev** [comment]
Можете по аналогии попробовать сделать для русского:
https://github.com/AndreyAkinshin/Russian-Phd-LaTeX-Dissertation-Template/blob/master/biblio/biblatex.tex#L267-L270
