### ISSUE TITLE
В англоязычной литературе заменять "Т." на "V." и "С." на "Р."

### ISSUE THREAD

**Issue by nickkolok** [odomanov/biblatex-gost#25]
MWE:
```latex
\documentclass[12pt]{article}
\usepackage[T1,T2A]{fontenc}
\usepackage[utf8]{inputenc}
\usepackage[english,russian]{babel}

\usepackage{filecontents}
\begin{filecontents}{lorentz.bib}
@article{lorentz1948contribution,
  ids={L},
    AUTHOR = {Lorentz, G. G.},
     TITLE = {A contribution to the theory of divergent sequences},
   JOURNAL = {Acta Mathematica},
    VOLUME = {80},
      YEAR = {1948},
     PAGES = {167--190},
      ISSN = {0001-5962},
   MRCLASS = {40.0X},
  MRNUMBER = {0027868 (10,367e)},
MRREVIEWER = {R. P. Agnew},
  number={1},
  publisher={Springer},
  hyphenation={english},
  language={english},
  langid={english},
}

@book{banach2001theory_rus,
  title={Теория линейных операций},
  author={Банах, С},
  year={2001},
  publisher={Регуляр. и хаот. динамика М},
  pages={256},
}
\end{filecontents}{lorentz.bib}

\usepackage[backend=biber,language=autobib,style=gost-numeric,sorting=none]{biblatex}
\addbibresource{lorentz.bib}
%\DefineBibliographyExtras{russian}{\DeclareFieldFormat{pages}{C. #1}}

% This does not work
%\DeclareFieldFormat{pages}{\expandafter\iflanguage{russian}{C.}{P.}~#1}

\begin{document}
\cite{*}
\printbibliography
\end{document}
```
Ожидание: в английской ссылке "P." и "V.", в русской "С."
Реальность:
![изображение](https://user-images.githubusercontent.com/5008131/77105261-65f7cd00-6a2e-11ea-9043-c1ca13ff4cc2.png)

### А что говорит ГОСТ?
ГОСТ 7.1-2003
> 4.9 Язык библиографического описания, как правило, соответствует языку выходных сведений документа. Отдельные элементы в описании могут быть приведены на языке библиографирующего учреждения.

Прошу фикса и помощи в создании временной заплатки :)

**Comment by LSinev** [comment]
Язык библиографирующего утверждения - русский. Так что фикса можете и не дождаться, тем более, что совместимости с ГОСТ 7.1 не обещали.
И на Россию теперь распространяется ГОСТ Р 7.0.100-2018 как бы вместо ГОСТ 7.1-2003, который на несколько стран СНГ.

Вот такие опции вызова пакета не помогали?
```tex
language=autobib,% получение языка из babel/polyglossia, default: autobib % если ставить autocite или auto, то цитаты в тексте с указанием страницы, получат указание страницы на языке оригинала
autolang=other,% многоязычная библиография
clearlang=true,% внутренний сброс поля language, если он совпадает с языком из babel/polyglossia
```

**Comment by nickkolok** [comment]
@LSinev , спасибо большое! Помогли опции.
![изображение](https://user-images.githubusercontent.com/5008131/77108642-a0179d80-6a33-11ea-94b2-275d64bce642.png)

**Comment by odomanov** [comment]
Чтобы автоматика с переключением языка работала, нужно ещё везде добавлять `langid`. У вас в описании `banach2001theory_rus` его нет.

**Comment by nickkolok** [comment]
@odomanov , спасибо, но как ни странно, у меня это работает: язык по умолчанию в документе русский; загружены все требуемые языки в преабуле; все иностранные записи - с явным указанием языка, все русские - без `langid`.
