### ISSUE TITLE
 \mkrelatedstring will be deprecated in favour of \mkrelatedstringtext

### ISSUE THREAD

**Issue by moewew** [odomanov/biblatex-gost#27]
Apologies for writing in English.

Due to https://github.com/plk/biblatex/issues/1057 (and in particular https://github.com/plk/biblatex/commit/f5a096a6395e274b3af9d01d5fb4aecddeff138d) we are planning to deprecate `\mkrelatedstring` in favour of the new command `\mkrelatedstringtext`.

This style uses `\mkrelatedstring` in https://github.com/odomanov/biblatex-gost/blob/master/tex/latex/biblatex-gost/biblatex-gost.def and https://github.com/odomanov/biblatex-gost/blob/master/tex/latex/biblatex-gost/bbx/gost-standard.bbx.

In order to avoid deprecation warnings it is recommended to switch over to the new command.

This could be done by defining the new `\mkrelatedstringtext` yourself if it is not defined already (easiest probably with `\providecommand`)
```latex
\providecommand*{\mkrelatedstringtext}[1]{{{\mainlang #1}}}
```
and
switching all uses of the form
```latex
\bibstring[\mkrelatedstring]
```
to
```latex
\bibstring[\mkrelatedstringtext]
```
and all uses of the form
```latex
\begingroup
\mkrelatedstring%
\lbx@initnamehook{#1}%
\endgroup
```
to
```latex
\mkrelatedstringtext{\lbx@initnamehook{#1}}%
```

See for example what I did for `biblatex-ext`: https://github.com/moewew/biblatex-ext/commit/df5c2b454a999ff0332c84bac34781b9a4683ea8.

**Comment by odomanov** [comment]
>
> Apologies for writing in English.
>
Please don't worry, it's absolutely fine!

Thank you for the warning, I'll make changes shortly.


Due to plk/biblatex#1057 <https://github.com/plk/biblatex/issues/1057> (and

**Comment by odomanov** [comment]
Done in the version 1.19.
