### ISSUE TITLE
Spurious space in sparsely-populated @book entry

### ISSUE THREAD

**Issue by moewew** [odomanov/biblatex-gost#29]
Via https://tex.stackexchange.com/q/568427/35864

Consider
```latex
\documentclass{article}
\usepackage[backend=biber,style=gost-inline]{biblatex}


\begin{filecontents}{\jobname.bib}
@book{Millimetron,
  author     = {John Millimetron},
  title      = {A title of the first book},
}
\end{filecontents}
\addbibresource{\jobname.bib}

\begin{document}
\autocite{Millimetron}
    
\printbibliography
\end{document}
```

This produces

![(Millimetron J. A title of the first book )](https://user-images.githubusercontent.com/6755835/97205942-67edef80-17b8-11eb-9744-ad0304533b72.png)

The problem seems to be an uncommented line end in

https://github.com/odomanov/biblatex-gost/blob/bab15c8e2a1380207d63a092376434a4de9e77f9/tex/latex/biblatex-gost/bbx/gost-standard.bbx#L1333-L1351

specifically line 1341

https://github.com/odomanov/biblatex-gost/blob/bab15c8e2a1380207d63a092376434a4de9e77f9/tex/latex/biblatex-gost/bbx/gost-standard.bbx#L1341

**Comment by odomanov** [comment]
Yes, thank you. This is clearly the bug.
