### ISSUE TITLE
опция movenames

### ISSUE THREAD

**Issue by NovA80** [odomanov/biblatex-gost#3]
В свежей установке TeXLive-2016 на Windows (там biblatex-3.7, biblatex-gost-1.10) опция movenames=false не работает. При этом на другом Linux-компьютере со старой версией TeXLive-2015 (biblatex-3.0, biblatex-gost-1.2) опция действует согласно документации.

**Comment by odomanov** [comment]
Да, не работает. Я исправлю в ближайшее время.

**Comment by odomanov** [comment]
Должно быть исправлено в версии 1.11. Я её послал на CTAN.

**Comment by MarinaSD** [comment]
Не знаю,  сюда ли пишу. 

Мне нужно поменять в библиографии англ и русские источники. Выбрала наиболее простой для себя вариант - переместить их внутри sort в файле bbl. Вот только нумерация осталась прежней: тереь сначала идут работы с номерами 50-100, а после них английский 1-49 ((( .

Помогите, пожалуйста.
