### ISSUE TITLE
Double punctuation in op cit citations

### ISSUE THREAD

**Issue by moewew** [odomanov/biblatex-gost#30]
Via https://tex.stackexchange.com/q/568427/35864

Consider
```latex
\documentclass{article}
\usepackage[backend=biber,style=gost-inline]{biblatex}


\begin{filecontents}{\jobname.bib}
@book{Millimetron,
  author     = {John Millimetron},
  title      = {A title of the first book},
}
\end{filecontents}
\addbibresource{\jobname.bib}
\addbibresource{biblatex-examples.bib}

\begin{document}
\autocite{Millimetron}

\autocite{sigfridsson}

\autocite{Millimetron}
    
\printbibliography
\end{document}
```

The third citation reads

![(Millimetron J.. Op. cit.)](https://user-images.githubusercontent.com/6755835/97206368-ec407280-17b8-11eb-967b-92ff5c8a78e8.png)

with two '.'s.

I could work around the issue by removing the `\bibsentence` in

https://github.com/odomanov/biblatex-gost/blob/bab15c8e2a1380207d63a092376434a4de9e77f9/tex/latex/biblatex-gost/cbx/gost-inline.cbx#L427-L434

(it should be implied by `\labelnamepunct` in the standard settings) but I'm not sure if that is generally acceptable, because I don't know why the  `\bibsentence` is there in the first place.

**Comment by odomanov** [comment]
Thank you for spotting it!

I don't remember why it's there. I need to contemplate a little bit.

**Comment by odomanov** [comment]
I added `\bibsentence` in Feb 2014 because "op. cit" was not capitalized without it. Now it seems that `\labelnamepunct` is enough. Perhaps something has changed.

**Comment by moewew** [comment]
> 
> 
> I added `\bibsentence` in Feb 2014 because "op. cit" was not capitalized without it. Now it seems that `\labelnamepunct` is enough. Perhaps something has changed.

Thought as much. If `\labelnamepunct` is something like `\addperiod\space` or some other sentence-ending punctuation, then the following bibstring should be capitalised automatically. There is a caveat here, though. The code uses `\setunit*`, which does nothing if the previous `\printfield` or `\printnames` didn't print anything. So you may end up with punctuation that was in the buffer prior to the invocation of the macro which may or may not contain a punctuation command that triggers capitalisation. In most situations you will probably end up with `\labelnamepunct`, which will probably be defined with `\add...` commands that trigger capitalisation. But this is not guaranteed from within `cite:opcit` alone. (I thought you might have added the explicit `\bibsentence` to address some weird edge case.)

If the 'op cit' should always be capitalised (no matter if the previous punctuation requires it) it might be easier to force the capitalised string with
```latex
\bibcpstring[\mkibid]{opcit}
```
instead of
```latex
\bibstring[\mkibid]{opcit}
```
But unless you know of a pathological test case, I'd probably just remove the `\bibsentence%` and let `biblatex`'s automatic (which is usually quite good) handle the rest.

---

BTW `\labelnamepunct` has been deprecated in favour of the context-sensitive delimiter `nametitledelim`.

**Comment by odomanov** [comment]
`labelnamepunct` is precisely equal to `\addperiod\space`. 
Ok, I've just removed `\bibsentence`, my tests show nothing suspicious so far.
I submitted corrections to CTAN.

**Comment by odomanov** [comment]
I didn't know about context-sensitive delimiters. I feel I need to reread the biblatex manual regularly to stay on top)))

**Comment by moewew** [comment]
For the most interesting changes you don't have to read all 300-something pages of the manual. The changelog at the end together with the more technical http://mirrors.ctan.org/macros/latex/contrib/biblatex/CHANGES.md and style-author-focussed https://github.com/plk/biblatex/wiki/Changes-to-the-standard-styles should keep you up to date with the most relevant things. Of course it helps to review the code of the standard styles from time to time to see what has changed if you want your style to keep up with the standard styles.

**Comment by odomanov** [comment]
Oh, thank you. I did know about the former but not the latter, it's really useful.
