### ISSUE TITLE
Проблема со стилями

### ISSUE THREAD

**Issue by sdorof1** [odomanov/biblatex-gost#35]
Все стили, кроме gost-numeric, в тексте отображаются неверно.

```
\documentclass[11pt]{article}
\usepackage[utf8]{inputenc}
\usepackage[english, russian]{babel}
\usepackage[bibstyle=gost-inline]{biblatex}
\addbibresource{references.bib}
\begin{document}

\cite{ref1,ref2}

\printbibliography  
\end{document}
```

![Снимок экрана от 2021-04-12 15-59-38](https://user-images.githubusercontent.com/6806825/114398602-a5003f80-9ba8-11eb-8dbd-453a2775035b.png)

[test.zip](https://github.com/odomanov/biblatex-gost/files/6296881/test.zip)

**Comment by odomanov** [comment]
`bibstyle` переключает стиль библиографии, но не цитат. Вам нужно написать `citestyle=gost-inline` или `style=gost-inline`.

**Comment by sdorof1** [comment]
Ок, спасибо!

**Comment by sdorof1** [comment]
В документации сказано, что gost-inline помещает ссылки в тексте в круглых скобках, но у меня скобок почему-то нет:
![Снимок экрана от 2021-04-12 21-17-13](https://user-images.githubusercontent.com/6806825/114441826-86b03900-9bd4-11eb-99a4-6cea8a4c3ad3.png)

Можно ли отделять цитаты от текста скобками, а еще лучше, жирным шрифтом?

**Comment by odomanov** [comment]
> В документации сказано, что gost-inline помещает ссылки в тексте в круглых скобках, но у меня скобок почему-то нет:

`\cite` это команда для вывода без скобок. Используйте `\autocite`.

> Можно ли отделять цитаты от текста скобками, а еще лучше, жирным шрифтом?

Конечно, можно, но с ходу не скажу как.
