### ISSUE TITLE
Журнал требует какой-то странный "ГОСТ", можно ли его сделать быстро?

### ISSUE THREAD

**Issue by nickkolok** [odomanov/biblatex-gost#37]
Из редакции пришло письмо:

> оформить список литературы по ГОСТу, используемого в журнале

Что это такое - непонятно, но есть [пример](http://www.vestnik.vsu.ru/pdf/physmath/2021/03/2021-03-07.pdf):
![image](https://user-images.githubusercontent.com/5008131/142491918-188272e3-0f4a-4338-a73a-744de6223783.png)
Основное тут то, что впереди зачем-то ещё раз выносится фамилия. Ещё сокращения журналов - но с этим справится и [`shortmathj`](https://ctan.org/pkg/shortmathj).

Кроме того, там происходит какое-то мракобесие с транслитерацией:
![image](https://user-images.githubusercontent.com/5008131/142510668-deee9e1c-7ed5-4416-a7b1-9168a60c03b1.png)
Нет ли случайно данных, почему так странно (двумя разными способами) транслитерируются фамилии?

Буду очень признателен за указание на возможность сделать что-то из этого быстро (если таковая существует).

**Comment by odomanov** [comment]
> 
> 
> Из редакции пришло письмо:
> 
> > оформить список литературы по ГОСТу, используемого в журнале
> 
> Что это такое - непонятно, но есть [пример](http://www.vestnik.vsu.ru/pdf/physmath/2021/03/2021-03-07.pdf): ![image](https://user-images.githubusercontent.com/5008131/142491918-188272e3-0f4a-4338-a73a-744de6223783.png) Основное тут то, что впереди зачем-то ещё раз выносится фамилия. 

Попробуйте gost-alphabetic, мне кажется, там это можно сделать.

> Ещё сокращения журналов - но с этим справится и [`shortmathj`](https://ctan.org/pkg/shortmathj).
> 
> Кроме того, там происходит какое-то мракобесие с транслитерацией: ![image](https://user-images.githubusercontent.com/5008131/142510668-deee9e1c-7ed5-4416-a7b1-9168a60c03b1.png) Нет ли случайно данных, почему так странно (двумя разными способами) транслитерируются фамилии?

Видимо, первое это как автор транслитерирует, а второе -- какие-то общие правила.

Саму транслитерацию я как-то через lua делал, уже не помню как. Что-то вроде этого: https://tex.stackexchange.com/questions/285610/create-a-mapping-for-transliteration-from-cyrillic-to-latin-in-lualatex.

> 
> Буду очень признателен за указание на возможность сделать что-то из этого быстро (если таковая существует).

**Comment by odomanov** [comment]
На транслитерацию, кстати, есть гост: https://docs.cntd.ru/document/1200026226.

**Comment by nickkolok** [comment]
Спасибо! Собственно, дальнейшие поиски (а снова мелькнуло требование делать именно так, упоминая авторов дважды - теперь речь о диссертации) привели к следующим удивительным открытиям. (Да, про это написано в п.2 документации - но реальность считает иначе.)

Существует два ГОСТа на библографию: [ГОСТ 7.0.5-2008](https://ifap.ru/library/gost/7052008.pdf) и [ГОСТ Р 7.0.100-2018](https://fs.guap.ru/docs/titul/primer_bibl.pdf). Причём в первом написано, что если ссылка только для поиска, то применяется первый, а если ещё и для идентификации - то второй (вернее, тот, взамен которого он был введён - [ГОСТ 7.1-2003](https://docs.cntd.ru/document/1200034383)) - см. п. 4.5.

Разница наглядно:
ГОСТ 7.0.5-2008 (biblatex-gost):
![image](https://user-images.githubusercontent.com/5008131/149683903-2fa18cfa-ee7f-4f4c-841c-afc17313e6a7.png)

ГОСТ Р 7.0.100-2018:
![image](https://user-images.githubusercontent.com/5008131/149683955-dd3748a9-90b9-4863-b6f1-562e3213a20b.png)
![image](https://user-images.githubusercontent.com/5008131/149683988-33ba93eb-4525-4b6a-9292-e2f1e34c7d96.png)

> > Основное тут то, что впереди зачем-то ещё раз выносится фамилия.

> Попробуйте `gost-alphabetic`, мне кажется, там это можно сделать.

Прошу меня простить, но разве `gost-numeric` от `gost-alphabetic` отличается не только тем, что у первого `[1]`, а у второго `[Ор1984]` ?

Разные журнал, ЧСХ, стоят за разные ГОСТы. Например, скопусные "Чебышевский сборник" и "Владикавказский математический журнал" - за "наш" ГОСТ 7.0.5-2008, а ВАКовский "Вестник ВГУ. Физика. Математика" - за ГОСТ Р 7.0.100-2018. 

С диссертациями всё получается ещё интереснее. [ГОСТ 7.0.11-2011](http://www.iki.rssi.ru/rus/gost.pdf) на диссертации прямо требует (п. 5.6.7, абз. 2) использовать для библиографии ГОСТ 7.1-2003 - то есть, в настоящее время, заменивший его ГОСТ Р 7.0.100-2018. То есть - c ходу `biblatex-gost` использовать для оформления диссертации **нельзя**.

Пока писал - нашёл решение, которое и оставлю здесь "для протокола":
```tex
\makeatletter
\ltx@iffilelater{biblatex-gost.def}{2017/02/01}%
{\toggletrue{bbx:gostbibliography}%
\renewcommand*{\revsdnamepunct}{\addcomma}}{}
\makeatother
```

Насколько я понимаю, диссовет должно устроить.

По-моему, можно закрывать issue :)

**Comment by nickkolok** [comment]
Кроме того, я предлагаю включить пятистрочный лайфхак выше в руководство и дать на него ссылку из раздела 2, где говорится про ГОСТ 7.1-2003 и ГОСТ Р 7.0.100-2018 (последний, кстати, стОит упомянуть на всякий случай). Мол, так и так, вообще-то эти ГОСТы не поддерживаются, но если очень хочется - то кастаните вот это, авось прокатит.

**Comment by LSinev** [comment]
В документации, вроде описано https://github.com/odomanov/biblatex-gost/blob/master/doc/latex/biblatex-gost/biblatex-gost.tex#L2229-L2252
Может там какой-то момент непонятен или недостаточно прокомментирован?

**Comment by nickkolok** [comment]
Да нет, всё в порядке. Прошу прощения, был невнимателен.
