### ISSUE TITLE
ГОСТ требует, чтобы страницы сокращались до одной буквы

### ISSUE THREAD

**Issue by IntoLighter** [odomanov/biblatex-gost#38]
Это из документации к опции otherlangs.
Какие, блин, страницы?

**Comment by odomanov** [comment]
В чём вопрос?

**Comment by IntoLighter** [comment]
Что подразумевается под страницами? Как страницу можно в букву, в принципе, отобразить?

**Comment by odomanov** [comment]
а, понятно
спасибо, исправлю
