### ISSUE TITLE
Кириллическое тире в библиографии

### ISSUE THREAD

**Issue by denshd** [odomanov/biblatex-gost#39]
Приветствую.

В документации к стилю написано, что при указании доп. полей `language = {russian}` и `langid = {russian}`, длинное (em-dash) тире заменяется на кириллическое `\cyrdash`. Также существует механизм ручного задания через `\providecommand*{\BibDash}{}`.

Однако в моём примере в обоих случаях (в т.ч. явного задания через `BibDash`) em-dash не заменяется на кириллическое.

Возможно выставлены неправильные настройки, хотя следовал документации.

`lualatex`, `TeX 3.141592653 (TeX Live 2022)`.

mve:
`main.tex`
```
\documentclass[11pt]{article}

\usepackage{polyglossia}
\setdefaultlanguage[forceheadingpunctuation=false, spelling=modern, babelshorthands=true]{russian}
\setotherlanguage{english}

\usepackage[xcharter]{fontsetup}

\bibliographystyle{ugost2008}
\usepackage[
    backend = biber,
    bibencoding = utf8,
    style = gost-numeric,
    sorting = none,
    language = auto,
    autolang = langname
]{biblatex}

\addbibresource{bibliography.bib}



\begin{document}
    Пустой текст для проверки вместе с "--- русским тире и с --- обычным тире.

    \nocite{*}
    \providecommand*{\BibDash}{~\cyrdash{}}
    \printbibliography
\end{document}
```

`bibliography.bib`
```
@article{mve,
    title = {Проверка русского \cyrdash{} и обычного --- тире},
    author = {Иванов, Иван Иванович},
    journal = {Nature},
    volume = {176},
    number = {9},
    pages = {931--963},
    year = {2006},
    language = {russian},
    langid = {russian}
}

@article{ackermann2022high,
    title={High-energy and ultra-high-energy neutrinos: A Snowmass white paper},
    author={Ackermann, Markus and Bustamante, Mauricio and Lu, Lu and Otte, Nepomuk and Reno, Mary Hall and Wissel, Stephanie and Agarwalla, Sanjib K and Alvarez-Mu{\~n}iz, Jaime and Batista, Rafael Alves and Arg{\"u}elles, Carlos A and others},
    journal={Journal of High Energy Astrophysics},
    volume={36},
    pages={55--110},
    year={2022},
    publisher={Elsevier},
    language=english,
    langid = {english},
    langidopts = {variant=british}
}
```

result:
![image](https://github.com/odomanov/biblatex-gost/assets/71206238/58855f8c-ca83-49f8-afe5-19119403a340)

**Comment by LSinev** [comment]
Справедливости ради стоит заметить, что уже года два как пришли к выводу, что вся эта тема с кириллическим тире (по части длины), это неверно истолкованное наследие конвертации первых шрифтов в LaTeX на русский (или близко к тому). Потому, если суть запроса в желании соответствовать русской типографике в части длины тире, то расслабьтесь (тут стоит отметить, что, например, в «американской» традиции публикаций тире не отбивают пробелами).

Нет под рукой ссылки на ту дискуссию, где упорный исследователь провел изыскания и показал, что длина тире традицией не нормирована, но одно из последствий той дискуссии нашлось: https://github.com/kia999/babel-russian/issues/4#issue-775802635

EDIT: Нашлась дискуссия. https://github.com/reutenauer/polyglossia/issues/445 Очень рекомендую почитать всю, как там развивалось, и чем закончилось (мне особенно запомнилось доверие авторитету создателей первых русифицированных шрифтов LaTeX).

**Comment by denshd** [comment]
Большое спасибо!
Да, суть запроса была в желании соответствовать русской типографике в части длины тире. В своё время, видимо, сбила меня с толку эта страничка в [вики](https://ru.wikibooks.org/wiki/LaTeX/%D0%98%D1%81%D0%BF%D0%BE%D0%BB%D1%8C%D0%B7%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D0%B5_%D1%80%D0%B0%D0%B7%D0%BD%D1%8B%D1%85_%D1%8F%D0%B7%D1%8B%D0%BA%D0%BE%D0%B2), в которой в разделе `babelshorthands` и указывалось "кириллическое тире".
Так что, думаю, вопрос более не актуален.

...

И всё же, `\BibDash` почему-то не заменяет тире)

**Comment by odomanov** [comment]
В biblatex-gost это определяется так:
```latex
\DeclareBibliographyOption{blockpunct}[emdash]{%
  \ifstrequal{#1}{emdash}
    {\renewcommand*{\newblockpunct}{\addperiod\addnbspace\textemdash\space\bibsentence}}
    {\renewcommand*{\newblockpunct}{\addperiod\space\bibsentence}}
}
```
Т.е. по умолчанию тире равно `\textemdash`, и чтобы изменить, нужно переопределить `\newblockpunct`. 

Что касается пробелов до и после тире, то это специальная пунктуация для библиографии и в ГОСТе на библиографию пробелы не регламентируются. В любом случае, TeX эти пробелы выставляет по своему усмотрению. Не думаю, что здесь нужно что-то менять.

`\BibDash` это из другого пакета и здесь не работает.

**Comment by odomanov** [comment]
Кстати, об этом немного в вики написано: https://github.com/odomanov/biblatex-gost/wiki/Как-убрать-тире-между-частями-библиографического-описания

**Comment by denshd** [comment]
С вопросом разобрался, спасибо!
