### ISSUE TITLE
Недостаточно строгая проверка версии biblatex

### ISSUE THREAD

**Issue by amonakov** [odomanov/biblatex-gost#4]
В настоящий момент biblatex-gost проверяет наличие biblatex-3.3 (проверка в tex/latex/biblatex-gost/bbx/gost-standard.bbx:7-14), но на самом деле требуется как минимум biblatex-3.5, так как команды \datecircaprint и другие не были определены в более ранних релизах biblatex.

(заметил эту проблему на дистрибутиве gentoo, где сейчас доступен texlive-2016, но максимальная версия biblatex лишь 3.4; к сожалению, из-за слабой проверки версии было не очень просто понять, в чём загвоздка)

**Comment by odomanov** [comment]
Да, спасибо. Я исправил.
