### ISSUE TITLE
Оформление ссылок на архивные источники

### ISSUE THREAD

**Issue by daakhmerov** [odomanov/biblatex-gost#41]
Олег, здравствуйте!
Хотел уточнить такой момент: в истории (и, думаю, в смежных дисциплинах) мы указываем ссылки в следующем формате: 
Трубецкой Н.С. (1925). Письмо П.Н.Савицкому от 12.05 // ГАРФ. Ф. 5783. Оп. 1. Д.312 Л.1-2. Соответственно, ГАРФ здесь — архив, Ф — номер (иногда — и литера) фонда, Д — дело, Л — листы. Кажется, что ни один стиль цитирования для biblatex такого функционала не предлагает (см., например, для Chicago — https://tex.stackexchange.com/questions/354056/biblatex-chicago-bib-entries-and-citations-for-historical-archives).
Я хотел узнать, возможно ли реализовать подобный функционал в biblatex? И если да, то, может быть, подскажете идеи, как это можно сделать? Думаю, среди историков аудитория latex'а небольшая, поэтому решение в любом случае будет нишевым.

**Comment by odomanov** [comment]
Это зависит от того, что вы хотите. Самое простое -- вписать это всё в `volume`. Там проверяется, если `volume` не число, то оно выводится как есть, без всякой обработки. Т.е. вы можете туда вписать всё, что хотите.

Если же нужно что-то более сложное (например, вывод для других языков), то я делал это для патентов, можете посмотреть. Это не идеал, но в качестве примера можно использовать.

**Comment by daakhmerov** [comment]
Спасибо, попробую!
