### ISSUE TITLE
Не перемещать единственного автора в сведения об ответственности

### ISSUE THREAD

**Issue by techkryan** [odomanov/biblatex-gost#42]
Например, вместо

> Плунгян В. А. Корпус как инструмент и как идеология: о некоторых уроках современной корпусной лингвистики / В. А. Плунгян // Русский язык в научном освещении. — М., 2008. — № 2. — С. 7—20.

сделать

> Плунгян В. А. Корпус как инструмент и как идеология: о некоторых уроках современной корпусной лингвистики // Русский язык в научном освещении. — М., 2008. — № 2. — С. 7—20.

MRE:
```
\documentclass{report}
\usepackage[T1,T2A]{fontenc}
\usepackage[utf8]{inputenc}
\usepackage[english,main=russian]{babel}

\usepackage[
  backend=biber,
  style=gost-numeric,
  autolang=other,
  language=auto,
  minnames=3,
]{biblatex}
\addbibresource{refs.bib}

\begin{document}
  \toggletrue{bbx:gostbibliography}
  \printbibliography
  \nocite{*}
\end{document}
```
refs.bib
```
@article{плунгян2008,
  title={Корпус как инструмент и как идеология: о некоторых уроках современной корпусной лингвистики},
  author={Плунгян, В. А.},
  journal={Русский язык в научном освещении},
  number={2},
  pages={7--20},
  year={2008},
  publisher={Институт русского языка им. В.~В. Виноградова РАН},
  address={М.}
}
```

**Comment by odomanov** [comment]
Это ошибка какая-то, я посмотрю.

Но вообще, вам точно нужно `\toggletrue{bbx:gostbibliography}`?

**Comment by techkryan** [comment]
> Но вообще, вам точно нужно `\toggletrue{bbx:gostbibliography}`?

В противном случае авторы не переносятся в сведения об ответственности.
![img-2024-06-21-13-34-26](https://github.com/odomanov/biblatex-gost/assets/126440135/8dee91ed-f680-42e6-aa59-b1bdc1a7de47)

Вот что требуется:

1. Если автор 1, то писать его имя в начале, и не помещать его в свед. об отв.
2. Если авторов 2 или 3, то писать имя первого в начале, и перечислять всех авторов в свед. об отв.
3. Если авторов 4, то выносить только название, и перечислять всех 4 в свед. об отв.
4. Если авторов ≥5, то выносить только название, и перечислять первых 3 + [и др.] в свед. об отв.

К желаемому поведению можно приблизиться, если выставить еще и `maxnames=4`. ` \toggletrue{bbx:gostbibliography}` отрабатывает как надо, за исключением первого условия.

**Comment by odomanov** [comment]
Всё-таки это не ошибка, это соответствует ГОСТу. А то, что вы хотите, не соответствует, насколько я понимаю. Простого способа это сделать я не вижу, а вставлять это в пакет не нужно (т.к. не соответствует ГОСТу).

**Comment by techkryan** [comment]
Во всяком случае спасибо вам за ваш многолетний труд. Привет из Томска)
