### ISSUE TITLE
Помогите плиз с номерами

### ISSUE THREAD

**Issue by MarinaSD** [odomanov/biblatex-gost#6]
Мне нужно поменять в библиографии англ и русские источники. Выбрала наиболее простой для себя вариант - переместить их внутри sort в файле bbl. Вот только нумерация осталась прежней: тереь сначала идут работы с номерами 50-100, а после них английский 1-49 ((( .

Помогите, пожалуйста.

**Comment by LSinev** [comment]
И инструкция из wiki https://github.com/odomanov/biblatex-gost/wiki/Как-сделать%2C-чтобы-русскоязычные-источники-предшествовали-остальным не помогла?

**Comment by MarinaSD** [comment]
Может я что неправильно делаю ((( подскажите, плиз.
Вот что делаю: 
открыла bbl , врезала кусок  с русскими работами, переставила его в начало внутри sort. 
Вопробовала prftexify  - он переписал файл bbl.

Вернула свои изменения (русские в начало), запистила latex. Получила в начале русс, потом англ, но нумерация прежняя.

Оставила изменения в bbl, и добавила вот этот кусов в начало:
\DeclareSourcemap{
  \maps[datatype=bibtex]{
    \map{
      \step[fieldsource=langid, match=russian, final]
      \step[fieldset=presort, fieldvalue={a}]
    }
    \map{
      \step[fieldsource=langid, notmatch=russian, final]
      \step[fieldset=presort, fieldvalue={z}]
    }
  }
}

Запустила latex, Не помогло .

Вставила вместо в bbl перед sort  этого куска тот, что написан далее по ссылке со словами "следующее усложнение". Повторила latex. не помогло

**Comment by MarinaSD** [comment]
@LSinev Подскажите, пожалуйста, как воспользоваться этой инструкцией? 
На примере файла шаблона.
Я поменяла в bbl c "none" на "nyt" засунула кусок кода (см ниже) в конец файла bibliopreamble , запустила pdftexify, bib, pdftexify --- библиография вообще не постриолась... и сслыки отобразились в виде соответствующего кода..

Понимаю, тчо возможно где-то туплю, но пожалуйтса, напишите "делай раз- делай два- делай три".


\DeclareSourcemap{
  \maps[datatype=bibtex]{
    \map{
      \step[fieldset=langid, fieldvalue={tempruorder}]
    }
    \map[overwrite]{
      \step[fieldsource=langid, match=russian, final]
      \step[fieldsource=presort, 
        match=\regexp{(.+)}, 
        replace=\regexp{aa$1}]
    }
    \map{
      \step[fieldsource=langid, match=russian, final]
      \step[fieldset=presort, fieldvalue={az}]
    }
    \map[overwrite]{
      \step[fieldsource=langid, notmatch=russian, final]
      \step[fieldsource=presort, 
        match=\regexp{(.+)}, 
        replace=\regexp{za$1}]
    }
    \map{
      \step[fieldsource=langid, notmatch=russian, final]
      \step[fieldset=presort, fieldvalue={zz}]
    }
    \map{
      \step[fieldsource=langid, match={tempruorder}, final]
      \step[fieldset=langid, null]
    }
  }
}

**Comment by LSinev** [comment]
Не знаю. Мне самому не надо было решать такое никогда. Я просто знаю, где инструкция от автора пакета лежит.

**Comment by odomanov** [comment]
Вам нужно вставить `\DeclareSourcemap` в ваш `.tex` файл, в преамбулу после `\usepackage[...]{biblatex}`. После этого удалите все вспомогательные файлы (bbl, bcf, aux и пр.) и сделайте 

pdflatex
biber
pdflatex

Если не получится, присылайте ваши файлы, нужно смотреть подробности.
Что такое bibliopreamble?
