### ISSUE TITLE
Настройка отображения имен авторов

### ISSUE THREAD

**Issue by Greyvend** [odomanov/biblatex-gost#7]
1. Как можно убрать пробелы между именем и отчеством в списке литературы: `Колмогоров А. Н.` => `Колмогоров А.Н.` ?

2. Как можно добавить неразрывный пробел между фамилией и инициалами: `Колмогоров А. Н.` => `Колмогоров~А.Н.` ?

**Comment by odomanov** [comment]
Посмотрите в документации biblatex раздел "3.13.4 Name Parts and Name Spacing". Там описаны разделители для имён.
