### ISSUE TITLE
Запись по ГОСТ 7.1

### ISSUE THREAD

**Issue by yarror** [odomanov/biblatex-gost#8]
Здравствуйте! Можно ли как-нибудь приблизить библиографическую запись к ГОСТ 7.1, т.е., чтобы при наличие двух или более авторов, вначале стоял только первый автор, а потом дублировался вместе с остальными после косой черты в области сведений об ответственности? Да, я знаю, что стиль biblatex-gost заточен под ГОСТ 7.0.5—2008. Написана диссертация с использованием этого пакета, но в диссертационном совете сказали, что "список литературы не по ГОСТ". Хотел поспорить, но перечитал ГОСТ 7.0.11-2011 "Диссертация и автореферат диссертаци", там сказано: "Библиографические записи оформляются в соответствии с требованиями ГОСТ 7.1 и ГОСТ 7.80".

**Comment by odomanov** [comment]
Да, это, видимо, придётся сделать, хотя это не слишком согласуется с `biblatex`.  Я отправил на CTAN версию 1.14, посмотрите, там кое-что сделано.

**Comment by yarror** [comment]
Спасибо за ответ!

**Comment by yarror** [comment]
Попробовал с версией 1.14. При использовании
\newrefcontext[sorting=ntvy]
\printbibliography[env=gostbibliography] всё равно в области заглавия стоят три автора, если их трое, тоже самое и  \toggletrue{bbx:gostbibliography}. При этом в этой версии стала работать опция maxnames=1. Но не совсем так, как хотелось: с ней оставляет только одного автора, про других пишет [и др.], если их два или три. Если четыре и более, то переносит первого автора в область сведений об ответственности и пишет  [и др.]. 
Попробовал использовать  maxbibnames=3, но они с maxnames=1 не совсем дружат: работает только та, которая стоит второй.

**Comment by odomanov** [comment]
У меня работает в обоих случаях. Какой у Вас стиль и какая версия biblatex? Я проверял с biblatex 3.7.

**Comment by odomanov** [comment]
Это тестовый файл, который у меня работает.

[gostbibliography.zip](https://github.com/odomanov/biblatex-gost/files/976211/gostbibliography.zip)

**Comment by yarror** [comment]
Я дико извиняюсь, на работе немного задёргали, неправильно поставил пакет (тупо скопировал папку biblatex-gost, в директории doc и tex, даже не открывая её), поэтому всё вышеописанное касалось версии 1.13. Сейчас добрался дома до компьютера, попробовал собрать с версией 1.14, всё отлично работает без всяких шаманств с maxnames и т.д. и именно так как нужно. Версия biblatex 3.7. Огромное спасибо!!!

**Comment by odomanov** [comment]
Ну и хорошо. пусть пока так и будет. Учтите, что это временная версия, она с `gost-authoryear` не работает. Не понимаю пока, как лучше сделать.
