### ISSUE TITLE
Оформление нормативно-правовых актов biblatex-gost

### ISSUE THREAD

**Issue by klouh** [odomanov/biblatex-gost#9]
Не учитывается сортировка по иерархии нормативно-правовых актов. Даже в технической литературе, это очень важный момент. Т.е. хотелось бы корректной работы с НПА (Конституция, законы (ФКЗ, ФЗ), подзаконные акты и т.д.).

**Comment by LSinev** [comment]
Есть шанс ускорить воплощение хотелки путем следующих манипуляций:
1. Сделать примеры записей всех желаемых вариантов нормативно-правовых актов.
2. Привести примеры текущей обработки biblatex-gost (в разных сортировках, если имеет значение). То есть, по сути, состояние «как есть сейчас».
3. Привести примеры желаемого результата обработки этих записей и их сортировки. То есть, по сути, состояние «как хочется, чтобы было».
4. Сослаться на конкретные пункты [ГОСТ 7.1-2003](https://github.com/AndreyAkinshin/Russian-Phd-LaTeX-Dissertation-Template/blob/master/Documents/GOST%207.1-2003.pdf), [ГОСТ 7.0.5-2008](http://diss.rsl.ru/datadocs/doc_291tu.pdf) и [ГОСТ 7.80-2000](http://www.nsu.ru/library/images/NIP_k/7.80_2000.pdf), в которых была описана корректная процедура сортировки по иерархии нормативно-правовых актов.

**Comment by odomanov** [comment]
Может быть, пример какой-то есть? Не очень понятно, какая это сортировка.

**Comment by klouh** [comment]
Нормативные документы имеют следующую юридическую силу:
1.Международные документы
2. Конституция РФ
3.Кодексы.
4. Федеральные законы
5.Указы Президента
6.Постановления Правительства
7.Постановления гос. Думы
8.Распоряжения Министерств и ведомств
9.Инструкционные письма
А также все нормативно - правовые акты субъектов не должны противоречить федеральным законам.  Пример отсюда: https://otvet.mail.ru/question/20676777
Проблемы начинаются с  иерархией подзаконных НПА в рамках одной группы.  Свои курсовые и дипломные посеял, корпоративную информацию не могу публиковать. Найду, что-нибудь отпишусь.

**Comment by odomanov** [comment]
Всё равно непонятно. Я совершенно не юрист, поэтому без подробностей непонятно. Вы хотите, чтобы документы сортировались по юридической силе? Т.е. нужно завести отдельное поле вроде "тип документа" и сортировать по нему? Или эту силу можно по какому-то номеру определить?

**Comment by klouh** [comment]
Да, поле тип документа хороший вариант. Сортировка нпа должна обязательно осуществляться прежде всего по юр. Силе, а затем по др. реквизитам.

-----Исходное сообщение-----
От: "odomanov" <notifications@github.com>
Отправлено: ‎19.‎06.‎2017 20:53
Кому: "odomanov/biblatex-gost" <biblatex-gost@noreply.github.com>
Копия: "Yaroslav Antropov (Victorovich)" <kklouhh@gmail.com>; "Author" <author@noreply.github.com>
Тема: Re: [odomanov/biblatex-gost] Оформление нормативно-правовых актов biblatex-gost (#9)

Всё равно непонятно. Я совершенно не юрист, поэтому без подробностей непонятно. Вы хотите, чтобы документы сортировались по юридической силе? Т.е. нужно завести отдельное поле вроде "тип документа" и сортировать по нему? Или эту силу можно по какому-то номеру определить?

**Comment by LSinev** [comment]
> Сортировка нпа должна обязательно осуществляться прежде всего по юр. Силе, а затем по др. реквизитам.

Это противоречит, по-видимому, требованиям ГОСТ на любые виды библиографии или затекстовых ссылок.
Тем не менее, сам `biblatex` предоставляет возможность использовать специальные поля в bibtex-записях для воздействия на их сортировку (`indexsorttitle`, `presort`, `sortkey`, `sortname`, `sortshorthand`, `sorttitle`, `sortyear`). Если их работа не модифицирована `biblatex-gost`, то вполне возможно ими воспользоваться.

**Comment by odomanov** [comment]
Да, ГОСТ это не регулирует, и непонятно насколько это стандартно. Может быть, какой-то другой ГОСТ есть? Неясно, нужно ли это вносить в пакет.
В любом случае, можно воспользоваться полями, как сказал @LSinev или определить свою сортировку через `\DeclareSortingScheme`. Можно ещё попробовать `\DeclarePresort`.
Возможно, под это нужно сделать отдельный пакет.

**Comment by Stasroot1** [comment]
Что касается сортировки НПА по юридическому весу... 
Я не профи в области кодинга, однако может можно сделать таким образом: 1. Использовать специальные поля biblatex, например sortkey и sortname, и еще для даты. В первое поле указать "вес" НПА от 0 до 15-40. Во второе поле указать тип НПА (Международный, общероссийский, региональный, муниципальный, локальный или рабочий). В третье поле с датой указать дату первого принятия документа.
Сортировку осуществлять в следующем порядке: Сначала по типу (sortname), потом по весу (sortkey) после по дате.

Сортировку по типу предоставить пользователю методом корректировки какого то конфигурационного файла в котором задать значения этим весам. Нпример: вес=0 это международный НПА ратифицированный и подписанный Президентомм РФ, вес 1= международный НПА. вес 2 = Конституция РФ. 3=Конституция какого либо государства. 4= Кодексы. 5=ФКЗ и так далее.  Сортировщик в итоге должен отсортировать данные из *.bib от меньшего к большему.  Имейте ввиду, что далеко не все международные законы действуют на территории РФ, и не все они выше по своей юридической силе чем Конституция РФ. По этой причине какие то международные НПА будут в итоге над конституцией РФ, какие то под ней.  В работе вполне может упоминаться несколько конституций (например работы по правовым системам нескольких государств одновременно). При этом для международных НПА возможно не нужен отдельный тип (международный), т.к. это, возможно, сделает не корректную сортировку по типам/весам.  Идальше внутри отсортированных групп пересортировать по дате первого приёма документа.

**Comment by Stasroot1** [comment]
Относительно нужности внесения в пакет: по факту ВУЗы требуют такой сортировки в письменных работах (курсовые, дипломы). Если требовани по такой сортировке и явных указаний на это в ГОСТах нет, то наличие такой сортировки в других работах не будет возброняться.

**Comment by Stasroot1** [comment]
Относительно нужности внесения в пакет: по факту ВУЗы требуют такой сортировки в письменных работах (курсовые, дипломы). Если требовани по такой сортировке и явных указаний на это в ГОСТах нет, то наличие такой сортировки в других работах не будет возброняться.

**Comment by Stasroot1** [comment]
Относительно нужности внесения в пакет: по факту ВУЗы требуют такой сортировки в письменных работах (курсовые, дипломы). Если требовани по такой сортировке и явных указаний на это в ГОСТах нет, то наличие такой сортировки в других работах не будет возброняться.

**Comment by LSinev** [comment]
https://tex.stackexchange.com/questions/410348/author-index-using-biblatex-with-oscola-style
Люди пишут отдельные пакеты поверх библатеха для, например, запис британских правовых документов.

**Comment by odomanov** [comment]
Всё-таки  это предмет для отдельного пакета. Библатех на это и рассчитан --- всегда можно дописать под себя. Даже стили, которые идут с самим библатехом, его авторы рассматривают только как образец, а не какой-то стандарт.

Я закрываю ветку.
